classDiagram
class PresentationLayer {
    <<Interface>>
    +ServiceAPI
}
class BusinessLogicLayer {
    + UserModel()
    + PlaceModel()
    + ReviewModel()
    + AmenityModel()
    + BusinessRules()
}
class PersistenceLayer {
    +DatabaseAccess
    +UserRepository
    +PlaceRepository
    +ReviewRepository
    +AmenityRepository
}
PresentationLayer --> BusinessLogicLayer : Uses Facade Pattern
BusinessLogicLayer --> PersistenceLayer : Database Operations
